### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xasos** [jonleung/distraction-free-facebook-messenger#13]
Hi Jon, just wondering what this project is licensed on. Planning on building a FB messenger productivity suite and would love to build on top of this.

Thanks!

**Comment by jonleung** [comment]
Hey @xasos, really sorry about the delayed response on this! I [just added](https://github.com/jonleung/distraction-free-facebook-messenger/commit/1fd3e28150573d520fc88bf4307be3ba4c0c0380) the MIT License to this project.
